### ISSUE TITLE
Cointainers in Long Range Delivery Drones

### ISSUE THREAD

**Issue by OldStarchy** [tburrows13/FreightForwarding#14]
If I set a logistic request for empty containers in a LRDD Request Depot I get the message "Containers are too heavy for logistic robots to carry - request has been cleared", but if I set the request using a constant combinator it works fine, actually we've had the request going for a while now so if this is fixed we'll have to change our factory a bit.

**Comment by OldStarchy** [comment]
Hold that thought, I could be wrong, it might have been someone else that put the containers in the depo

**Comment by tburrows13** [comment]
You are correct, it is possible to request containers (full and empty) for both LRDD and standard logibots by bypassing the gui with circuit control. Unfortunately there’s not much I can do about this except for checking all the requesters every so often, which wouldn’t be great for UPS. I might do that at some point, but it isn’t there currently.
