### ISSUE TITLE
Krastorio 2 integration: orange science named wrong

### ISSUE THREAD

**Issue by AriaMoradi** [tburrows13/FreightForwarding#24]
I am playing Krastorio 2 and FF mod pack together. The orange tech card is named "Transport science pack" which seems to be wrong, it should be named "Transport tech card" following pattern.

This can lead to confusion when trying to progress beyond the green tech.

**Comment by RedRafe** [comment]
Fixed from 1.8.4 already

**Comment by fgardt** [comment]
fixed by #21 to be exact
