### ISSUE TITLE
Tip says that aircraft can carry empty containers, but not actually possible ingame

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [tburrows13/FreightForwarding#25]
![image](https://github.com/tburrows13/FreightForwarding/assets/14184826/d0f78c19-fb94-4577-b6cb-c0135839d89f)

> Spidertrons and aircraft can carry empty containers, but not loaded ones

but, you can't actually do it in the game:

![image](https://github.com/tburrows13/FreightForwarding/assets/14184826/f4b0c255-79fb-4e20-b898-ddf3e4f65914)

one of those is wrong. not sure which.

**Comment by tburrows13** [comment]
By "Aircraft", it means the aircraft from the included [Lex's Aircraft](https://mods.factorio.com/mod/lex-aircraft) mod, not the long range delivery drones :)

**Comment by SIGSTACKFAULT** [comment]
@tburrows13 In that case you should clarify the tip
