### ISSUE TITLE
Krastorio 2 compability 

### ISSUE THREAD

**Issue by Dag-Rui** [tburrows13/FreightForwarding#8]
Got an error when attempting to load krastorio 2: "attempt to index field 'ic-load-logistic-network'" in data-final-fixes.lua.

**Comment by tburrows13** [comment]
This has already been fixed for the next version, but for the time being, it works if you add [Long range delivery drones](https://mods.factorio.com/mod/Long_Range_Delivery_Drones).

**Comment by Dag-Rui** [comment]
Awesome, thanks :)
